
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './db-types';

const SUPABASE_URL = "https://kiynbthegdpnlbphuafj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpeW5idGhlZ2RwbmxicGh1YWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzgyNzQsImV4cCI6MjA2MjA1NDI3NH0.MPW8jDixflbXvr9V5WW_-IdgWCYveRX9t0xsQf1U8GU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
